### ISSUE TITLE
视频教程在什么地方

### ISSUE THREAD

**Issue by longfeide2008** [nmgwddj/duilib_tutorial#1]
视频教程在什么地方，没有看到，有没有交流群可以一起交流的。

**Comment by nmgwddj** [comment]
抱歉，视频教程没有录制完成，个人事物比较多耽搁了。
我并不提倡交流群的方式沟通，一个是交流群信息闭塞一个问题可能产生多次询问和多次答复。这一点社区明显要比群交流的方式要好很多。

**Comment by longfeide2008** [comment]
> 抱歉，视频教程没有录制完成，个人事物比较多耽搁了。
> 我并不提倡交流群的方式沟通，一个是交流群信息闭塞一个问题可能产生多次询问和多次答复。这一点社区明显要比群交流的方式要好很多。

非常的感谢，期待你的大作，社区指的是？

**Comment by nmgwddj** [comment]
@longfeide2008 github 难道不是一个很好的社区吗。☺

**Comment by longfeide2008** [comment]
> @longfeide2008 github 难道不是一个很好的社区吗。☺

期待你的大作，大概什么时候会更新视频呢？

**Comment by nmgwddj** [comment]
@longfeide2008 可能不会基于官方原版来制作视频教程。预计在第二季度试着录制一部分。
