### ISSUE TITLE
图片不能正常显示

### ISSUE THREAD

**Issue by Oscar-Xu** [nmgwddj/duilib_tutorial#5]
阅读你写的教程，图片不能正常显示
![image](https://user-images.githubusercontent.com/3304715/87222632-e8264b80-c3a7-11ea-91d7-4c3ab053e6b7.png)

**Comment by nmgwddj** [comment]
Github 对国内用户不是特别友好，尝试连个其他 VPN。

**Comment by Oscar-Xu** [comment]
oh. thank a lot for your remind.
